CREATE TABLE ordered_item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   quantity INTEGER,
   item_id BIGINT,
   code INTEGER UNIQUE,
   active BOOLEAN,
   cart_id BIGINT,
   CONSTRAINT pk_ordered_item PRIMARY KEY (id)
);

CREATE TABLE cart_ordered_item (
  cart_id BIGINT NOT NULL,
   ordered_item_id BIGINT NOT NULL
);

CREATE TABLE cart (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   total_value FLOAT,
   code INTEGER UNIQUE,
   description VARCHAR(255),
   active BOOLEAN,
   CONSTRAINT pk_cart PRIMARY KEY (id)
);

CREATE TABLE item (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   code INTEGER UNIQUE,
   value_item DECIMAL,
   description VARCHAR(255),
   active BOOLEAN,
   CONSTRAINT pk_item PRIMARY KEY (id)
);


ALTER TABLE ordered_item ADD CONSTRAINT FK_ORDERED_ITEM_ON_CART FOREIGN KEY (cart_id) REFERENCES cart (id);

ALTER TABLE ordered_item ADD CONSTRAINT FK_ORDERED_ITEM_ON_ITEM FOREIGN KEY (item_id) REFERENCES item (id);