CREATE TABLE item_products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   quantity INTEGER,
   product_id BIGINT,
   active BOOLEAN,
   order_id BIGINT,
   CONSTRAINT pk_item_products PRIMARY KEY (id)
);

CREATE TABLE orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   total_value FLOAT,
   description VARCHAR(255),
   active BOOLEAN,
   CONSTRAINT pk_orders PRIMARY KEY (id)
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   name VARCHAR(255),
   code INTEGER UNIQUE,
   value_product DECIMAL,
   description VARCHAR(255),
   active BOOLEAN,
   CONSTRAINT pk_products PRIMARY KEY (id)
);

ALTER TABLE item_products ADD CONSTRAINT FK_ITEM_PRODUCTS_ON_ORDER FOREIGN KEY (order_id) REFERENCES orders (id);

ALTER TABLE item_products ADD CONSTRAINT FK_ITEM_PRODUCTS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id);